In [13]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5] ,dtype=float)  # Need to be same data type
print(vector)
matrix = np.array([[1,2,3],[4,5,6]], dtype=int)  # must be n*m   mต้องเท่ากันทุกแถว
print(matrix)

[1. 2. 3. 4. 5.]
[[1 2 3]
 [4 5 6]]


In [14]:
# Access to values
print(vector[3:])
print(vector[::2])
print(vector[2:3])
vector[0] = 999
print(vector)

[4. 5.]
[1. 3. 5.]
[3.]
[999.   2.   3.   4.   5.]


In [ ]:
print(matrix[1,2])
print(matrix[0,1])

# 0-D array = scalar
# 1-D array = vector
# 2-D array = matrix
# N-D array = tensor (N = number > 2)

6
2


## Numpy Attributes

In [21]:
arr = np.array([[1,2,3],[4,5,6]] ,dtype=np.int16)

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int16


In [25]:
zeros = np.zeros((3,5), dtype=int)
print(zeros)
print(zeros.dtype)

ones = np.ones((3,3,3), dtype=int)
print(ones)
print(ones.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int64
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
int64


In [36]:
empty = np.empty((3,5), dtype=np.int16)
print(empty)

zeros_empty = np.zeros_like(empty)
print(zeros_empty)

[[   92    63    63    92    67]
 [   58    92    85   115   101]
 [  114   115     0 -2950   718]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [38]:
print(np.arange(10))
print(np.arange(5,10))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 2 4 6 8]


In [40]:
print(np.linspace(0,10,num=10, dtype=np.float16))

[ 0.     1.111  2.223  3.334  4.445  5.555  6.668  7.777  8.89  10.   ]
